### PR TITLE
Tribunal specific form fields

### PR DESCRIPTION
**Pull request by himal-mandalia**

### CODE REVIEW

**Comment by tatyree** [comment]
After discussion, HM is going to break out the conditionals into separate partials.

**Comment by himal-mandalia** [comment]
Partials refactored per section. Internationalisation merge in via develop, translations added for new fields.

**Comment by aldavidson** [comment]
My only quibble with this now is a minor one - that the translation keys no longer match the file path, and so have to have the full translation path hard-coded in each key - e.g. in  app/views/decisions/form_sections/_judges_fields.html.haml

`t('decisions.form.judges_heading')`

 rather than 

`t('.heading')`

...which would then be looked up in the scope decisions.form_sections.judges_fields by Rails.

**Comment by himal-mandalia** [comment]
Scoped!

**Pull request merged**
